### ISSUE TITLE
error while want to search on discord

### ISSUE THREAD

**Issue by OORDINARY12** [kimcore/simpleYT#3]
`(node:4368) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of null
    at module.exports (C:\Users\Administrator\Desktop\dc\node_modules\simpleyt\src\index.js:7:75)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:4368) UnhandledPromiseRejectionWarning: Unhandled promise rejection.`

**Comment by kimcore** [comment]
Can reproduce, working on a fix

**Comment by kimcore** [comment]
Fixed in 1.0.6, please use the updated version.
